### ISSUE TITLE
Vérification des liens entre patient-réservation-consultation-medecin-fichesmedical

### ISSUE THREAD

**Issue by Pauline-Humbert** [GestionCabinetMedical/GestiondeRdv#7]
Faire les merges des branches individuelles avec la branche dev
Vérification sur dev que tout fonctionne bien ensemble (création des tables, instances, foreign key fonctionnelles etc...)
Vérification qu'il n'y a pas de bug si oui créer une autre issue pour dire que vous résolver tel bug sur la branche dev

**Comment by Maxremb** [comment]
Verification des associations entre chaque classe (gestion-rdv et admin) -> OK
