### ISSUE TITLE
Ajouter la doc et les logs manquant

### ISSUE THREAD

**Issue by Pauline-Humbert** [GestionCabinetMedical/GestiondeRdv#8]
Sur la branche dev (une fois fonctionnelle) après avoir "récolter" le travail de chaque branche :
Ajouter la Java doc sur les classes et méthodes 
Ajouter les logs manquant dans les différentes méthodes 
Ajouter dans les entités au sein de l'annotation @Column si unique est false ou true et si nullable est false ou true

**Comment by Sophie-Lmr** [comment]
Javadoc ajoutée dans toutes les classes et interfaces !

**Comment by Sophie-Lmr** [comment]
Vérification des contraintes unique/nullable dans les Entités... OK

**Comment by Pauline-Humbert** [comment]
Ajouter doc sur les méthodes make...Response DTO dans controller
